sonar.projectKey=Rental-Veh-Front
sonar.projectName=Rental Veh Front
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**

sonar.host.url=http://localhost:9000
sonar.token=sqp_2c63cdc7f882a34679a9944458b8d034a51a6b26